# Numpy

`NumPy` es una librería para hacer computos numéricos en Python. Es la base de muchas otras librerías científicas. Entre otras cosas, nos permite:

- Utilizar arreglos multidimensionales.
- Utilizar funciones matemáticas.
- Utilizar herramientas de álgebra lineal.

Necesitamos conocer esta librería (en concreto, el manejo de arreglos) para poder entender el funcionamiento de `pandas`. 

### Requisitos

Para esta clase necesitamos tener instalada la librería numpy:

```
pip3 install --upgrade numpy
```

Para comenzar a trabajar vamos a importar la librería y crear un pequeño arreglo de elementos aleatorios.

In [2]:
import numpy as np

data = np.random.randn(2,4)
data

array([[ 0.57461273,  1.60418394,  0.82681334, -1.42514022],
       [ 1.71205686,  0.53689462, -0.24577957, -0.0794689 ]])

A diferencia de una lista, podemos hacer operaciones matriciales, como multiplicar el arreglo `data` por un escalar:

In [3]:
data*10

array([[  5.7461273 ,  16.04183944,   8.26813339, -14.25140216],
       [ 17.12056862,   5.36894617,  -2.45779575,  -0.79468903]])

o sumarle una matriz:

In [4]:
data + data

array([[ 1.14922546,  3.20836789,  1.65362668, -2.85028043],
       [ 3.42411372,  1.07378923, -0.49155915, -0.15893781]])

### Crear arreglos

Podemos crear arreglos a partir de una lista:

In [5]:
data1 = [1, 1, 2, 3, 5]
arr1 = np.array(data1)
arr1

array([1, 1, 2, 3, 5])

In [6]:
data2 = [[1, 1, 2, 3], [5, 8, 13, 21]]
arr2 = np.array(data2)
arr2

array([[ 1,  1,  2,  3],
       [ 5,  8, 13, 21]])

Para preguntar el número de dimensiones utilizamos `ndim`. Para preguntar las dimensiones utilizamos `shape`.

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

### Accediendo a elementos

Para obtener un elemento:

In [14]:
arr1[2]

2

In [15]:
arr2[1][2]

13

In [16]:
# Podemos acceder de esta forma también.
arr2[1, 2]

13

Los arreglos son mutables:

In [17]:
arr1[3] = 300
arr1

array([  1,   1,   2, 300,   5])

In [18]:
arr2[1, 2] = 100
arr2

array([[  1,   1,   2,   3],
       [  5,   8, 100,  21]])

### arange

También tenemos un equivalente a `range` llamado `arange`, pero que genera un arreglo.

In [7]:
np.arange(2, 11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

### Operaciones sobre arreglos

Algunas operaciones que se pueden hacer sobre un arreglo son:

In [8]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [22]:
arr + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [23]:
(arr + 1) - arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
1 / arr

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [25]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

### _Slices_

Podemos extraer partes de un arreglo tal como en las listas. También podemos usar esto para cambiar los valores de dichos elementos.

In [26]:
arr = np.arange(3,15)
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr[3:6]

array([6, 7, 8])

In [29]:
arr[3:6] = 1
arr

array([ 3,  4,  5,  1,  1,  1,  9, 10, 11, 12, 13, 14])

### Indexando con booleanos

Podemos utilizar comparaciones booleanas con los arreglos:

In [10]:
arr = np.array([0, 0, 1, 1, 2, 2])
arr == 1

array([False, False,  True,  True, False, False])

Y usarlo para acceder a valores en otros arreglos. Vamos a crear un arreglo multidimensional e ingresar el arreglo anterior como índice:

In [11]:
arr2 = np.random.randn(6, 3)
arr2

array([[ 0.53274243, -0.06308258,  1.55085865],
       [ 0.28846094, -0.04432974, -0.6743501 ],
       [-0.21240705,  1.51668318, -1.13491428],
       [ 0.98661702,  0.1960152 ,  0.02286284],
       [-0.29600443, -0.14775093, -0.74068634],
       [-1.87840243, -0.19713132,  1.90861011]])

In [12]:
arr2[arr == 1]

array([[-0.21240705,  1.51668318, -1.13491428],
       [ 0.98661702,  0.1960152 ,  0.02286284]])

Y también podemos negar la condición:

In [33]:
arr2[~(arr == 1)]

array([[ 0.39754381, -1.29167182, -0.5411754 ],
       [-0.02392931, -1.11918671,  0.2881838 ],
       [-1.99903501, -1.9495602 ,  0.90343025],
       [-0.04137128,  1.2252531 , -0.34718251]])

### Transponer un arreglo

Es posible obtener la transpuesta de un arreglo rápidamente.

In [37]:
arr = np.random.randn(6, 3)
arr

array([[ 0.15920914,  0.05229821, -0.19296301],
       [-0.37946029,  0.122006  , -0.19017146],
       [-0.78677894, -0.35637733, -0.18941291],
       [-0.00765847,  2.04357794, -0.32941621],
       [ 0.89687296,  1.14051443, -0.69261992],
       [ 1.3606585 , -0.55382145,  0.15436516]])

In [38]:
arr.T

array([[ 0.15920914, -0.37946029, -0.78677894, -0.00765847,  0.89687296,
         1.3606585 ],
       [ 0.05229821,  0.122006  , -0.35637733,  2.04357794,  1.14051443,
        -0.55382145],
       [-0.19296301, -0.19017146, -0.18941291, -0.32941621, -0.69261992,
         0.15436516]])

### Otras funciones

Tenemos acceso a algunas funciones de estadística básicas. Por ejemplo `sum`, `mean` y `std` nos permiten respectivamente sacar la suma, el promedio y la desviación estándar de un arreglo.

In [39]:
arr = np.random.randn(10)
arr

array([ 0.89785463, -1.51262834, -1.63271519,  0.34629049, -0.52690398,
       -0.54982572,  0.5535778 ,  1.15683601,  0.12698068,  0.03332928])

In [40]:
arr.sum()

-1.107204342790007

In [41]:
arr.mean()

-0.11072043427900069

In [42]:
arr.std()

0.8943803603711583

También podemos ordenar:

In [43]:
arr.sort()
arr

array([-1.63271519, -1.51262834, -0.54982572, -0.52690398,  0.03332928,
        0.12698068,  0.34629049,  0.5535778 ,  0.89785463,  1.15683601])

Y pedir elementos distintos:

In [44]:
arr = np.array([0, 0, 1, 1, 2, 2])
np.unique(arr)

array([0, 1, 2])